Type: AWS::IAM::Role
Properties:
  RoleName: ${self:service}--dataEditor
  AssumeRolePolicyDocument:
    Version: '2012-10-17'
    Statement:
    - Effect: Allow
      Principal:
        Federated: cognito-identity.amazonaws.com
      Action: sts:AssumeRoleWithWebIdentity
      Condition:
        StringEquals:
          cognito-identity.amazonaws.com:aud:
            Ref: identityPool
        ForAnyValue:StringLike:
          cognito-identity.amazonaws.com:amr: authenticated


  Policies:
    - PolicyName: ${self:service}--dataEditor
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: appsync:GraphQL
            Resource:
              Fn::Join:
                - ''
                - - Fn::GetAtt: ["graphQLApi", "Arn"]
                  - /*

          - Effect: Allow
            Action:
              - s3:PutObjectAcl
              - s3:PutObject
              - s3:GetObjectAcl
              - s3:DeleteObject
              - s3:ListBucket

            Resource:
              - arn:aws:s3:::${file(../slscms-config.yml):bucket_name}/*

          - Effect: Allow
            Action:
              - mobileanalytics:PutEvents
              - cognito-sync:*
              - cognito-identity:*
            Resource:
              - "*"
