service:
  name: serverless-cms-dev

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: us-west-2

functions:
  resize:
    handler: functions/resize-images.resizeImages

    role: resizeRole

    events:
      - s3:
          bucket: ${self:service}
          event: s3:ObjectCreated:*
          rules:
            - prefix: images/temp/
            - suffix: .jpg

    environment:
      BUCKET: ${self:service},
      IMG_TABLE: ${self:service}-images

  createPage:
    handler: functions/create-page.createPage
    role: createPageRole
    environment:
      BUCKET: ${self:service}
      IMG_TABLE: ${self:service}-images
      PAGES_TABLE: ${self:service}-pages
      MENUS_TABLE: ${self:service}-menus


resources:
  Resources:
    resizeRole: ${file(./settings/roles/resizeRole.yml)}
    createPageRole: ${file(./settings/roles/createPageRole.yml)}

    imagesTable: ${file(./settings/tables.yml):imagesTable}
    pagesTable: ${file(./settings/tables.yml):pagesTable}
    menusTable: ${file(./settings/tables.yml):menusTable}
