imagesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:service}-images
    AttributeDefinitions:
      - AttributeName: gallery
        AttributeType: S
      - AttributeName: filename
        AttributeType: S

    KeySchema:
      - AttributeName: gallery
        KeyType: HASH
      - AttributeName: filename
        KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1


pagesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:service}-pages
    AttributeDefinitions:
      - AttributeName: name
        AttributeType: S

    KeySchema:
      - AttributeName: name
        KeyType: HASH

    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1


menusTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:service}-menus
    AttributeDefinitions:
      - AttributeName: name
        AttributeType: S

    KeySchema:
      - AttributeName: name
        KeyType: HASH

    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1

fragmentsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:service}-fragments
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S

    KeySchema:
      - AttributeName: id
        KeyType: HASH

    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
