fragmentsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:service}-fragments
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: type
        AttributeType: S

    KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: type
        KeyType: RANGE

    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
