Type: AWS::IAM::Role
Properties:
  RoleName: ${self:service}--sourceAppSyncRole
  AssumeRolePolicyDocument:
    Version: '2012-10-17'
    Statement:
      - Effect: Allow
        Principal:
          Service:
            - appsync.amazonaws.com
        Action: sts:AssumeRole
  Policies:
    - PolicyName: ${self:service}--updateDb
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - lambda:invokeFunction
            Resource:
              - Fn::GetAtt: ["ResolveNestedFragmentsLambdaFunction", "Arn"]
              - Fn::GetAtt: ["ResolvePageTypeLambdaFunction", "Arn"]
              - Fn::GetAtt: ["RenderLambdaFunction", "Arn"]
              - Fn::GetAtt: ["ResizeLambdaFunction", "Arn"]
              - Fn::GetAtt: ["BackupLambdaFunction", "Arn"]
              - Fn::GetAtt: ["RestoreFromBackupLambdaFunction", "Arn"]
              - Fn::GetAtt: ["GetBackupListLambdaFunction", "Arn"]
              - Fn::GetAtt: ["DeleteBackupsLambdaFunction", "Arn"]
