service:
  name: ${file(../slscms-config.yml):service_name}

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-stack-output
  - serverless-s3-sync
custom:
  output:
    file: ./stack.yml
    handler: scripts/client.handler
    
  webpack:
    includeModules: true # enable auto-packing of external modules

  s3Sync:
    - bucketName: ${file(../slscms-config.yml):bucket_name}
      bucketPrefix: templates/
      localDir: front_end/config/
    - bucketName: ${file(../slscms-config.yml):bucket_name}
      bucketPrefix: dist/
      localDir: front_end/public/
      acl: public-read # optional
      followSymlinks: true # optional
    - bucketName: ${file(../slscms-config.yml):bucket_name}
      bucketPrefix: admin/
      localDir: admin/build/
      acl: public-read # optional
      followSymlinks: true # optional
      defaultContentType: text/html # optional
      params: # optional
        - index.html:
            ContentType: text/html
        - "*.css":
            ContentType: text/css 

package:
  individually: true

provider:
  name: aws
  runtime: nodejs8.10

  stage: dev
  region: us-west-2

functions:
  resolvePageType:
    handler: functions/resolvePageType.resolvePageType
    role: readS3role
    environment:
      BUCKET: ${file(../slscms-config.yml):bucket_name}
  resolveNestedFragments:
    handler: functions/resolveNestedFragments.handler
    role: updateDbRole
    environment:
      FRAGMENTS_TABLE: ${self:service}-fragments
  backup:
    handler: functions/backup.handler
    role: backupRole
    environment:
      FRAGMENTS_TABLE: ${self:service}-fragments
      BUCKET: ${file(../slscms-config.yml):bucket_name}

  resize:
    handler: functions/resize-images.resizeImages
    role: resizeRole
    timeout: 10
    memorySize: 2048

    environment:
      BUCKET: ${file(../slscms-config.yml):bucket_name}
      FRAGMENTS_TABLE: ${self:service}-fragments
      GRAPHQL:
        Fn::GetAtt: ["graphQLApi", "GraphQLUrl"]

  render:
    handler: functions/renderPages.handler
    role: resizeRole

    environment:
      BUCKET: ${file(../slscms-config.yml):bucket_name}
      FRAGMENTS_TABLE: ${self:service}-fragments
      GRAPHQL:
        Fn::GetAtt: ["graphQLApi", "GraphQLUrl"]

resources:
  - ${file(./resources/resources.yml)}
  - ${file(./resources/graphql-api/createResolvers.js)}
  - ${file(./resources/outputs.yml)}