service:
  name: ${file(../slscms-config.yml):service_name}

package:
  individually: true
  excludeDevDependencies: false

# Add the serverless-webpack plugin
plugins:
  - serverless-plugin-typescript
  - serverless-plugin-include-dependencies
  - serverless-stack-output
  - serverless-s3-sync
custom:
  output:
    file: ./stack.yml
    handler: scripts/client.handler
    
  webpack:
    includeModules: true # enable auto-packing of external modules

  s3Sync:
    - bucketName: ${file(../slscms-config.yml):bucket_name}
      bucketPrefix: templates/
      localDir: front_end/config/
    - bucketName: ${file(../slscms-config.yml):bucket_name}
      bucketPrefix: dist/
      localDir: front_end/public/
      acl: public-read # optional
      followSymlinks: true # optional
    - bucketName: ${file(../slscms-config.yml):bucket_name}
      bucketPrefix: admin/
      localDir: admin/build/
      acl: public-read # optional
      followSymlinks: true # optional
      defaultContentType: text/html # optional
      params: # optional
        - index.html:
            ContentType: text/html
        - "*.css":
            ContentType: text/css 

provider:
  name: aws
  runtime: nodejs10.x

  stage: dev
  region: us-west-2

functions: 
  - ${file(./resources/functions.yml)}
  - ${file(./scripts/graphql/createFunctionResolvers.js)}

resources:
  - ${file(./resources/resources.yml)}
  - ${file(./scripts/graphql/createResolvers.js)}
  - ${file(./resources/outputs.yml)}