Type: AWS::IAM::Role
Properties:
  RoleName: ${self:service}--adminRole
  AssumeRolePolicyDocument:
    Version: '2012-10-17'
    Statement:
      - Effect: Allow
        Principal:
          Federated: cognito-identity.amazonaws.com
          Service:
            - lambda.amazonaws.com
            - appsync.amazonaws.com
        Action: sts:AssumeRole
  Policies:
    - PolicyName: ${self:service}--updateDb
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              Fn::Join:
                - ":"
                - - "arn:aws:logs"
                  - Ref: "AWS::Region"
                  - Ref: "AWS::AccountId"
                  - "log-group:/aws/lambda/*:*:*"

          - Effect: Allow
            Action:
              - dynamodb:BatchWriteItem
              - dynamodb:DeleteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:GetItem
              - dynamodb:BatchGetItem
              - dynamodb:Query
            Resource:
              Fn::Join:
                - ":"
                - - "arn:aws:dynamodb"
                  - Ref: "AWS::Region"
                  - Ref: "AWS::AccountId"
                  - table/${self:service}-fragments

          - Effect: Allow
            Action:
              - dynamodb:BatchWriteItem
              - dynamodb:DeleteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:GetItem
              - dynamodb:BatchGetItem
              - dynamodb:Query
            Resource:
              Fn::Join:
                - ":"
                - - "arn:aws:dynamodb"
                  - Ref: "AWS::Region"
                  - Ref: "AWS::AccountId"

          - Effect: Allow
            Action:
              - s3:PutObjectAcl
              - s3:PutObject
              - s3:GetObjectAcl
              - s3:DeleteObject
              - s3:ListBucket

            Resource:
              - arn:aws:s3:::${self:service}-public/*
