Type: AWS::IAM::Role
Properties:
  RoleName: ${self:service}-S3Dynamo
  AssumeRolePolicyDocument:
    Version: '2012-10-17'
    Statement:
      - Effect: Allow
        Principal:
          Service:
            - lambda.amazonaws.com
        Action: sts:AssumeRole
  Policies:
    - PolicyName: S3ReadWriteDynamoWrite
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              Fn::Join:
                - ":"
                - - "arn:aws:logs"
                  - Ref: "AWS::Region"
                  - Ref: "AWS::AccountId"
                  - "log-group:/aws/lambda/*:*:*"
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectAcl
              - s3:ListBucket
              - s3:PutObject
              - s3:PutObjectAcl
            Resource:
              - arn:aws:s3:::${self:service}-public/*
              - arn:aws:s3:::${self:service}-public
          - Effect: Allow
            Action:
              - s3:PutObjectAcl
              - s3:PutObject
            Resource:
              - arn:aws:s3:::${self:service}-public/public/images/thumbs/*
              - arn:aws:s3:::${self:service}-public/public/images/mobile/*
              - arn:aws:s3:::${self:service}-public/public/images/desktop/*
              - arn:aws:s3:::${self:service}-public/public/images/retina/*
              - arn:aws:s3:::${self:service}-public/public/images/*
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource:
              Fn::Join:
                - ":"
                - - "arn:aws:dynamodb"
                  - Ref: "AWS::Region"
                  - Ref: "AWS::AccountId"
                  - table/${self:service}-fragments
          - Effect: Allow
            Action: appsync:GraphQL
            Resource:
              Fn::Join:
                - ''
                - - Fn::GetAtt: ["graphQLApi", "Arn"]
                  - /*
